services:
  app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - redis
    environment:
      - PORT=3001
      - MONGO_URI=mongodb://mongodb:27017/moviesDB
      - REDIS_HOST=redis
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
